const Map<String, String> en = {
  "All": "All",
  "AlreadyHaveAnAccount": "Already have an account?",
  "And": "and",
  "Cancel": "Cancel",
  "ChangeInformation": "Change Information",
  "CreateMessage": "Create Message",
  "DateOfBirth": "Date of Birth",
  "DoNotHaveAnAccount": "Don't have an account?",
  "EnterYourDateOfBirth": "Enter your date of birth",
  "EnterYourEmail": "Enter your email",
  "EnterYourFullName": "Enter your full name",
  "EnterYourPassword": "Enter your password",
  "EnterYourPhoneNumber": "Enter your phone number",
  "Experience": "Experience Awesome chat",
  "ForgotYourPassword": "Forgot your password?",
  "Friends": "Friends",
  "FriendsList": "Friends List",
  "FullName": "Full Name",
  "IagreeToThe": "I agree to the",
  "Language": "Language",
  "LogOut": "Log Out",
  "Login": "Login",
  "MatchingMessages": "matching messages",
  "Messages": "Messages",
  "Notifications": "Notifications",
  "Password": "Password",
  "PhoneNumber": "Phone Number",
  "Policies": "policies",
  "Profile": "Profile",
  "Requests": "Requests",
  "Save": "Save",
  "SearchFriends": "Search friends…",
  "SearchMessages": "Search messages…",
  "SignInNow": "Sign in now",
  "SignUp": "Sign up",
  "SignUpNow": "Sign up now",
  "Terms": "terms",
  "Version": "Version"
};
