const Map<String, String> vi = {
  "All": "Tất cả",
  "AlreadyHaveAnAccount": "Đã có tài khoản?",
  "And": "và",
  "Cancel": "Hủy",
  "ChangeInformation": "Chỉnh sửa thông tin",
  "CreateMessage": "Tạo tin nhắn",
  "DateOfBirth": "Ngày sinh",
  "DoNotHaveAnAccount": "Chưa có tài khoản?",
  "EnterYourDateOfBirth": "Nhập ngày sinh của bạn",
  "EnterYourEmail": "Nhập email của bạn",
  "EnterYourFullName": "Nhập họ và tên của bạn",
  "EnterYourPassword": "Nhập mật khẩu của bạn",
  "EnterYourPhoneNumber": "Nhập số điện thoại của bạn",
  "Experience": "Trải nghiệm Awesome chat",
  "ForgotYourPassword": "Quên mật khẩu?",
  "Friends": "Bạn bè",
  "FriendsList": "Danh sách bạn bè",
  "FullName": "Họ Và Tên",
  "IagreeToThe": "Tôi đồng ý với",
  "Language": "Ngôn ngữ",
  "LogOut": "Đăng xuất",
  "Login": "Đăng nhập",
  "MatchingMessages": "tin nhắn phù hợp",
  "Messages": "Tin nhắn",
  "Notifications": "Thông báo",
  "Password": "Mật khẩu",
  "PhoneNumber": "Số điện thoại",
  "Policies": "chính sách",
  "Profile": "Trang cá nhân",
  "Requests": "Yêu cầu",
  "Save": "Lưu",
  "SearchFriends": "Tìm kiếm bạn bè…",
  "SearchMessages": "Tìm kiếm tin nhắn…",
  "SignInNow": "Đăng nhập ngay",
  "SignUp": "Đăng ký",
  "SignUpNow": "Đăng ký ngay",
  "Terms": "điều khoản",
  "Version": "Phiên bản ứng dụng"
};
