// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbrEjoCmjqDNVBKxQiq7G47GvwbEJOGM',
    appId: '1:515924180851:web:fcd41c31b8dec37f400f06',
    messagingSenderId: '515924180851',
    projectId: 'mock-chat-3c87e',
    authDomain: 'mock-chat-3c87e.firebaseapp.com',
    storageBucket: 'mock-chat-3c87e.appspot.com',
    measurementId: 'G-B7VRJTXM5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxQtC0EImnTFIbn5CFg0vOXWNqGvFZEE',
    appId: '1:515924180851:android:dd65f665490e0461400f06',
    messagingSenderId: '515924180851',
    projectId: 'mock-chat-3c87e',
    storageBucket: 'mock-chat-3c87e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmIhFVDZt7XMX5p4AMSWuSxm43QPsVIGE',
    appId: '1:515924180851:ios:678a0421f10c92de400f06',
    messagingSenderId: '515924180851',
    projectId: 'mock-chat-3c87e',
    storageBucket: 'mock-chat-3c87e.appspot.com',
    iosBundleId: 'com.example.mockChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmIhFVDZt7XMX5p4AMSWuSxm43QPsVIGE',
    appId: '1:515924180851:ios:678a0421f10c92de400f06',
    messagingSenderId: '515924180851',
    projectId: 'mock-chat-3c87e',
    storageBucket: 'mock-chat-3c87e.appspot.com',
    iosBundleId: 'com.example.mockChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkbrEjoCmjqDNVBKxQiq7G47GvwbEJOGM',
    appId: '1:515924180851:web:b73c74c2a436184f400f06',
    messagingSenderId: '515924180851',
    projectId: 'mock-chat-3c87e',
    authDomain: 'mock-chat-3c87e.firebaseapp.com',
    storageBucket: 'mock-chat-3c87e.appspot.com',
    measurementId: 'G-1SCXH7D8ML',
  );
}
